### ISSUE TITLE
Getting errors like undefined is not an object etc....

### ISSUE THREAD

**Issue by prashantvv** [yjy5264/react-native-pan-drawer#1]
Hello, I am new to react native,& I tried your project but I'm getting errors  while adding drawer to my component. Could you please explain me how to set up your drawer in the app.
Thanks

**Comment by yjy5264** [comment]
Show me your errors.

**Comment by prashantvv** [comment]
Sending the screenshot

**Comment by prashantvv** [comment]
<img width="256" alt="error" src="https://user-images.githubusercontent.com/22851097/30906968-0b3e5bdc-a397-11e7-923e-08c14cab3819.png">

**Comment by prashantvv** [comment]
error basically shows on 
this.drawer.open();
this.drawer.close();
this.drawer.toggle();
which I put in the constructor.

**Comment by prashantvv** [comment]
WHOLE CODE -

import React, { Component } from 'react';
import Drawer from 'react-native-pan-drawer'
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TextInput,
  ListView
 
} from 'react-native';

export default class Component2 extends Component {


constructor(){

super();
  this.drawer.open();
this.drawer.close();
this.drawer.toggle();
}
  render() {
    
    return (
    
<Drawer
    backgroundView = {() => <BackgroundView />}
    leftView = {() => <LeftView />}
    rightView = {() => <RightView />}
    ref = {ref => this.drawer = ref}
/>
  
    );
  }
  
}
AppRegistry.registerComponent('Component2', () => Component2);

**Comment by prashantvv** [comment]
I'll really appreciate if you help me out finding where I am doing wrong as I am new & constantly researching on react native to learn it.

**Comment by yjy5264** [comment]
you can only use this.drawer.open() after componentDidMount(), because the <Drawer /> has not Mount when constructor(). when constructor, this code (ref = {ref => this.drawer = ref}) has not been executed.

**Comment by prashantvv** [comment]
Hello, I am still getting the errors after it asks me to import BackgroundView,LeftView,RightView so i just add import {BackgroundView,LeftView,RightView} from 'react-native-pan-drawer';


![screenshot_1506584294](https://user-images.githubusercontent.com/22851097/30954530-20cb9e30-a44e-11e7-8e6b-e53920433281.png)

**Comment by yjy5264** [comment]
BackgroundView,LeftView,RightView is your component, not from react-native-pan-drawer. You can use `<View style={{flex: 1}} />` at first.

**Comment by prashantvv** [comment]
ok, sorry for my confusion, those are the components or the views that i want to implement. I did the changes and it works well. Thanks for helping me out.
